# Generated by Django 3.2 on 2021-04-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.FileField(upload_to='scan_files/')),
                ('file', models.FileField(upload_to='files/')),
                ('document', models.FileField(upload_to='document_files/')),
                ('number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('personal_number', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30, verbose_name='Gender')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('issuing_authority', models.CharField(max_length=255)),
            ],
        ),
    ]
