# Generated by Django 3.2 on 2021-04-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='passport',
        ),
        migrations.AddField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.person'),
        ),
    ]
