# Generated by Django 3.2 on 2021-04-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20210419_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document_files/'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='personal_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='scan_files/'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='task_app.person'),
        ),
    ]
