# Generated by Django 3.2 on 2021-04-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20210419_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
